### PR TITLE
Included user agent for download

### PR DESCRIPTION
**Pull request by jacokok**
Added user agent to curl download
`-A "itzg/minecraft-bedrock-server"`

Not sure if curlArgs could have been used but this seems to resolve the issue for now.

Fixes https://github.com/itzg/docker-minecraft-bedrock-server/issues/358

### CODE REVIEW

**Comment by mrgrosser** [comment]
Approved

**Review by itzg — APPROVED** [review]
Thanks. I hadn't realized this whole time that I only had the agent specified on the version lookup call further up.

**Comment by itzg** [comment]
> Not sure if curlArgs could have been used but this seems to resolve the issue for now.

Yeah adding to curlArgs would have been better, but that can be done in a follow up PR so you can make progress for now.

**Comment by sbogomolov** [comment]
@jacokok Thanks for fixing this.
@itzg Any chance we can get a release with this change? :)

**Comment by itzg** [comment]
> @jacokok Thanks for fixing this.
> 
> @itzg Any chance we can get a release with this change? :)

Its already pushed, but if you mean a tagged release then I'll kick that off too 😀

**Comment by itzg** [comment]
Tagged version is pushed https://github.com/itzg/docker-minecraft-bedrock-server/releases/tag/2024.9.0

**Comment by sbogomolov** [comment]
> Tagged version is pushed https://github.com/itzg/docker-minecraft-bedrock-server/releases/tag/2024.9.0

Thank you!

**Comment by Hossy** [comment]
Thank you!!

**Comment by c-gunther** [comment]
> Tagged version is pushed https://github.com/itzg/docker-minecraft-bedrock-server/releases/tag/2024.9.0

Could you please tag 2024.0.9 as latest as well.

**Comment by dlubs1733** [comment]
Same error on Synology NAS - struggling how to get around and get it back up and running? I thought with 9.0 being pushed to latest it would update automatically?

**Pull request merged**
