### PR TITLE
Adding permissions.json creation to bedrock server startup

### PR DESCRIPTION
**Pull request by hyperbolic2346**
This will use env variables for ops, members, and visitors to generate a permissions.json file at startup. It will smash it on each start of the container.

### CODE REVIEW

**Review by itzg — APPROVED** [review]
...and thank you for this one.

**Comment by itzg** [comment]
Oops, I was worried your other PR was close enough to cause conflicts.

**Comment by DaveMcCloud** [comment]
root@SandboxHost-xxxxxxxxx:/data# cat permissions.json
[
  {
    "permission": "operator",
    "xuid": "253xxxxxxxx61010"
  }
]

My permissions file looks like this after passing 253xxxxxxxx61010 in via OPS = 253xxxxxxxx61010 in the env variables.  However it doesn't seem to give me operator permissions.  Am I missing something obvious?

**Comment by itzg** [comment]
That looks right @DaveMcCloud , so it must be something about the bedrock server itself.

**Pull request merged**
