### PR TITLE
documentation: for addon install, no need to touch known_valid_known_packs.json

### PR DESCRIPTION
**Pull request by breakersun**

### CODE REVIEW

**Review by itzg — COMMENTED** [review]
That sounds great to have one last step. Since I have never been able to do the procedure myself, how certain are you the step isn't needed? Is there a reference you could link there?

**Comment by breakersun** [comment]
I just tried it by myself but sorry I don't have a reference for this.

Also, we can do this to make packs bonded to just one world:
- create `resouce_packs` & `behavior_packs` under `worlds/Bedrock level`, 
- Upload addons files to each directory
- and then create `world_resouce_packs.json` & `world_behavior_packs.json`, put UUIDs/Version in each JSON file

**Comment by breakersun** [comment]
I found `known_valid_known_packs.json` just gets updated by mcpe-server application itself every time it sees some new directory under `resource_packs` & `behavior_packs`.

**Comment by itzg** [comment]
> I just tried it by myself but sorry I don't have a reference for this.

Thanks, just thought I'd double check.

**Pull request merged**
